---
title: "leaflet"
output: html_document
---

```{r}
library(leaflet)
leaflet()

leaflet() %>% addTiles() # basic map of the world.... can zoom in!

leaflet() %>% addTiles() %>% setView(lng = -79.44, lat = 37.78, zoom = 12) # can draw to zoom into lexington ... popular in app projects in past to show to show a specific state or county! can find like state of va or something

leaflet() %>%
  setView(lng = -79.44, lat = 37.78, zoom = 12) %>%
  addProviderTiles(provider = providers$NASAGIBS.ViirsEarthAtNight2012) # to show earth at night .. tons of different provider tiles here ... ask chat!

# if you are wondering if it can do something, then ask!!!!

```


```{r}
lex <- data.frame( lat    = c(37.789444 , 37.787673  ,  37.785624  ) # this allows you to select locations on a map and then drop the teardrop markers and leave annotations
                 , lon    = c(-79.441725, -79.443623 , -79.441544  )
                 , place  = c("Lab"     , "Classroom", "Thai food!")
                 , rating = c(7         , 5          , 10          )
                 , stringsAsFactors = FALSE
                 )
leaflet(data = lex) %>% 
  setView(lng = -79.442778, lat = 37.783889, zoom = 12) %>%
  addTiles()

leaflet(data = lex) %>% # this allows you to drop a marker on a map
  addTiles() %>% 
  addMarkers(popup = ~place) # ~ means that you are refering to the data above

```


```{r}
leaflet(data = lex) %>%    # allows you to see how many teardrop markers are in that cluster
  setView(lng = -79.442778, lat = 37.783889, zoom = 10) %>% 
  addTiles() %>% 
  addMarkers(label = ~place, clusterOptions = markerClusterOptions())

```

USE THIS ONE! for seeing the states and the dominance of specialties in each state
```{r}
leaflet(data = lex) %>% addTiles() %>%
  addCircles(radius = ~rating, label = ~place) # GOOD FOR PICKING SPECIALTIES AND SEEING THE COUNTS PER STATE!!

```